version: "3.7"

networks:
  arqmedes:
    driver: bridge
    external: true

services:
  app:
    depends_on:
      - db
    build:
      args:
        user: arqmedes
        uid: 1000
      context: ./
      dockerfile: .docker/php7.4-fpm.dockerfile
    image: arqmedes/app
    container_name: arqmedes-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - arqmedes
  db:
    image: mysql:8.0.23
    container_name: arqmedes-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: arqmedes_alpha_test
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_PASSWORD: '12345678'
      MYSQL_USER: arqmedes_alpha
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 63333:3306
    volumes:
      - .docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - arqmedes
  nginx:
    image: nginx:1.17-alpine
    container_name: arqmedes-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
    networks:
      - arqmedes